config/routes.rb
Rails.application.routes.draw do
  get 'snatch/signup'
  get 'snatch/snatch'
  get 'snatch/about'
  get 'snatch/fail'
  get 'snatch/options'

  get 'snatch' => 'snatch#snatch'
  get 'about' => 'snatch#about'
  get 'signup' => 'snatch#signup'
  get 'options' => 'snatch#options'

  get '/auth/:provider/callback', to: 'snatch#callback'
  get '/auth/failure' , to: 'snatch#fail'

  root 'snatch#snatch'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/snatch_controller.rb
class SnatchController < ApplicationController
  require 'rest-client'
  require 'JSON'
  require 'net/http'
  require 'uri'

  # attr_accessor :p_name, :data
  attr_reader :p_name, :data
  attr_writer :p_name, :data

  def signup
  end

  def snatch
    @data = 999
  end

  def about
    @data ||= @data
  end

  def callback
    @response = request.env['omniauth.auth']
    @token = @response['credentials']['token']

    @header = {
      Accept: "application/json",
      Authorization: "Authorization: Bearer #{@response['credentials']['token']}"
    }

    @p_name = 'Fred'

    snatch
  end

      def get_me
      uri = URI.parse("https://api.spotify.com/v1/me")
      request = Net::HTTP::Get.new(uri)
      request["Accept"] = "application/json"
      request["Authorization"] = "Bearer #{@token}"

      req_options = {
        use_ssl: uri.scheme == "https",
      }

      response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
        http.request(request)
      end

      user = JSON.parse response.body
      @user_id = user['id']
    end

    def get_song
      if @user_id
        song = JSON.parse RestClient.get("https://api.spotify.com/v1/me/player/currently-playing", @header)
        @s_uri = song['item']['uri']
      end
    end

    def check_for_playlist
      if @user_id
        list = JSON.parse RestClient.get("https://api.spotify.com/v1/me/playlists?limit=50", @header)

        list['items'].each do |x|
            if x['name'] === @p_name
              puts x['name'] << ' Playlist found'
              @p_id = x['id']
              return
            end
          end
          create_playlist
        end
    end

    def create_playlist

      uri = URI.parse("https://api.spotify.com/v1/users/#{@user_id}/playlists")
      request = Net::HTTP::Post.new(uri)
      request.content_type = "application/json"
      request["Accept"] = "application/json"
      request["Authorization"] = "Bearer #{@token}"
      request.body = JSON.dump({
        "description" => "Your Snatched Playlist",
        "public" => false,
        "name" => "#{@p_name}"
      })

      req_options = {
        use_ssl: uri.scheme == "https",
      }

      response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
        http.request(request)
      end
      playlist = JSON.parse response.body
      @p_id = playlist['id']
      puts "#{@p_name} playlist created. ID: #{@p_id}"
    end

    def actually_snatch
      uri = URI.parse("https://api.spotify.com/v1/users/#{@user_id}/playlists/#{@p_id}/tracks?uris=#{@s_uri}")
      request = Net::HTTP::Post.new(uri)
      request["Accept"] = "application/json"
      request["Authorization"] = "Bearer #{@token}"

      req_options = {
        use_ssl: uri.scheme == "https",
      }

      response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
        http.request(request)
      end
      puts response.code
    end
    
    def snatch
      get_me
      get_song
      check_for_playlist
      actually_snatch
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snatch_helper.rb
module SnatchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snatch</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Snatch", root_path %></li>
        <!-- <li><%= link_to "Home", "welcome/index" %></li> -->
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "signup", signup_path %></li>
        <li><%= link_to "Link Spotify", '/auth/spotify' %></li>
        <li><%= link_to "Options", options_path %></li>
      </ul>

    <%= yield %>
    </div>
  </body>
</html>

app/views/snatch/about.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Snatch</h1>
    </div>
  </div>
  <hr>
</div>

<%= @data %>

<div class="container">
  <div class="row text-center">
    <div class="col-md-6 col-md-offset-3">Snatch is a little program I wrote to add whichever song I'm currently listening to a given playlist with a single gesture. The idea being that if one hears a song they like they can register it without taking more than a second off from what they are doing.</div>
  </div>
  <br>
  <!-- <img src="/app/assets/Images/Snatch.jpg" class="img-responsive" alt="Fenwick Elliott Office"/> -->
  <hr>
  <!-- <div class="row">
    <div class="text-center col-md-12">
      <div class="well"><strong>Blurb</strong></div>
    </div>
	</div> -->

app/views/snatch/callback.html.erb
<h1>Snatch#callback</h1>

<p> Snatch sucsessful!</p>

<p> <%= "Logged in as #{@response['uid']}. " %> </p>
<p> <%= "With token: #{@token}" %> </p>

<%= @response %>

app/views/snatch/fail.html.erb
<h1>Snatch#fail</h1>

<p> Whatever you tried to do, it didn't work.</p>

app/views/snatch/options.html.erb
<h1>Snatch#options</h1>

<p> Snatched playlist name: (text imput field)</p>
<p> Snatched playlist public? (checkbox)</p>
<p> Action if song has already been snatched? (dropdown menu)</p>

app/views/snatch/signup.html.erb
<div>
   <div id="login">
    <h1>First, log in to spotify</h1>
    <a href="/login">Log in</a>
   </div>
   <div id="loggedin">
   </div>
</div>

<script id="loggedin-template" type="text/x-handlebars-template">
   <h1>Logged in as {{display_name}}</h1>
   <img id="avatar" width="200" src="{{images.0.url}}" />
   <dl>
    <dt>Display name</dt><dd>{{display_name}}</dd>
    <dt>Username</dt><dd>{{id}}</dd>
    <dt>Email</dt><dd>{{email}}</dd>
    <dt>Spotify URI</dt><dd><a href="{{external_urls.spotify}}">{{external_urls.spotify}}</a></dd>
    <dt>Link</dt><dd><a href="{{href}}">{{href}}</a></dd>
    <dt>Profile Image</dt><dd>{{images.0.url}}</dd>
   </dl>
   <p><a href="/">Log in again</a></p>
</script>

app/views/snatch/snatch.html.erb
<h1>Snatch#snatch</h1>

<%= @data %>

Hi